param(
    [string]$Target = "."
)

# AI Coding workflow - Understanding layer (stage 1/2)
# Zero-dependency scanner producing docs/KNOWLEDGE.md as a project overview.

$ErrorActionPreference = 'Continue'

Write-Host "[explore] AI workflow understanding-layer nav generator"
Write-Host "[explore] target: $Target"
if (-not (Test-Path $Target)) { Write-Host "[explore] directory not found: $Target"; exit 3 }

$sb = New-Object System.Text.StringBuilder
function Ln([string]$s) { $script:sb.AppendLine($s) | Out-Null }

Ln ""
Ln "# Project Navigation (KNOWLEDGE)"
Ln ""
Ln ("- generated: " + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
Ln "- generated by: explore.ps1 (understanding layer) - scans only, never modifies source"

Ln ""
Ln "## 1. Top-level directory structure"
Ln ""
$top = Get-ChildItem $Target -Force -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notmatch '^(node_modules|\.git|dist|coverage|\.semgrep)$' }
foreach ($item in $top) {
    if ($item.PSIsContainer) {
        $fc = @(Get-ChildItem $item.FullName -Recurse -File -ErrorAction SilentlyContinue).Count
        $dc = @(Get-ChildItem $item.FullName -Directory -Recurse -ErrorAction SilentlyContinue).Count
        Ln ("- [DIR] " + $item.Name + "  (dirs=" + $dc + ", files=" + $fc + ")")
    } else {
        Ln ("- [FILE] " + $item.Name)
    }
}

Ln ""
Ln "## 2. Application entry files"
Ln ""
$entries = @(Get-ChildItem $Target -Recurse -File -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -notmatch 'node_modules' -and $_.Name -match '^(server|app|index|main)\.(js|ts|mjs)$' })
$baseLen = (Resolve-Path $Target).Path.Length
if ($entries.Count -gt 0) {
    foreach ($e in ($entries | Select-Object -First 8)) {
        Ln ("- " + $e.FullName.Substring($baseLen))
    }
} else {
    Ln "- (no server/app/index/main entry detected)"
}

Ln ""
Ln "## 3. Route endpoints (api/)"
Ln ""
$routeFiles = @(Get-ChildItem $Target -Recurse -Filter '*.js' -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -match '\\routes\\' -and $_.FullName -notmatch 'node_modules' })
if ($routeFiles.Count -gt 0) {
    foreach ($rf in $routeFiles) {
        Ln ("### " + $rf.Name)
        $text = Get-Content $rf.FullName -Raw -ErrorAction SilentlyContinue
        if ($text) {
            $rx = [regex]::Matches($text, "(?:router|app)\.(get|post|put|patch|delete)\s*\(\s*[^\x27\x22]*[\x27\x22][^\x27\x22]+[\x27\x22]")
            foreach ($m in $rx) { Ln ("- " + $m.Value) }
        }
    }
} else {
    Ln "- (no routes directory detected)"
}

Ln ""
Ln "## 4. Data models"
Ln ""
$modelFiles = @(Get-ChildItem $Target -Recurse -Filter '*.js' -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -match '\\models\\' -and $_.FullName -notmatch 'node_modules' })
if ($modelFiles.Count -gt 0) {
    foreach ($mf in $modelFiles) { Ln ("- " + $mf.Name) }
} else {
    Ln "- (no models directory detected)"
}

Ln ""
Ln "## 5. Constants / enums (whitelists)"
Ln ""
Ln "- (fill in during kickoff: sort whitelists, valid status/priority sets, etc.)"

Ln ""
Ln "## 6. Notes"
Ln ""
Ln "- This is a static overview. For a visual dependency graph use dependency-cruiser."
Ln "- Review this doc manually; you may edit it, but never write back to source."

$outDir = Join-Path (Get-Location) 'docs'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$outFile = Join-Path $outDir 'KNOWLEDGE.md'
[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "[explore] generated: $outFile"
exit 0