# TRAE security gate hook runner.
# Invoked by .git/hooks/pre-commit and .git/hooks/pre-push (generated by install-gate.ps1).
# Runs the semgrep gate (security-scan.ps1) against the whole repo.
param(
    [Parameter(Mandatory=$true)][ValidateSet('pre-commit','pre-push')][string]$Hook,
    [Parameter(Mandatory=$true)][string]$Repo,
    [switch]$Strict
)

$ErrorActionPreference = 'Stop'

$ScriptBase = $PSScriptRoot
if (-not $ScriptBase -or -not (Test-Path $ScriptBase)) {
    try { $ScriptBase = Split-Path -Parent $MyInvocation.MyCommand.Path } catch { }
}
if (-not $ScriptBase) { $ScriptBase = (Get-Location).Path }

$scan = Join-Path $ScriptBase 'security-scan.ps1'
$config = Join-Path $ScriptBase 'security-rules'
$semgrepignore = Join-Path $ScriptBase '.semgrepignore'

# Keep ignores effective regardless of target/detection: place a copy in the repo if missing.
$repoIgnore = Join-Path $Repo '.semgrepignore'
if (Test-Path $Repo) {
    if (-not (Test-Path $repoIgnore)) {
        Copy-Item $semgrepignore $repoIgnore -Force
        Write-Host "[gate] installed $repoIgnore"
    }
}

Write-Host "==== TRAE security gate ($Hook) ===="
& $scan -Target $Repo -Config $config -BlockWarnings:$Strict
$code = $LASTEXITCODE
if ($code -ne 0) {
    Write-Host "[gate] $Hook blocked: fix findings above before committing/pushing."
} else {
    Write-Host "[gate] $Hook OK"
}
exit $code