# Install the TRAE security gate into a git repository.
# Downloads no credentials; purely local. Safe to re-run (idempotent).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\_setup\install-gate.ps1
#   powershell -ExecutionPolicy Bypass -File .\_setup\install-gate.ps1 -Repo "C:\path\to\repo" -Strict
#
# Wired hooks:
#   .git/hooks/pre-commit  -> runs on `git commit`
#   .git/hooks/pre-push    -> runs on `git push`
# Each runs semgrep SAST. -Strict additionally blocks WARNING-level findings.
param(
    [string]$Repo,            # repo root; default: auto-discover upward from $PWD
    [switch]$Init,            # allow `git init` if $Repo is not yet a repository
    [switch]$Strict,          # treat warnings as blocking
    [switch]$DryRun           # only print what would be written
)

$ErrorActionPreference = 'Stop'
$setup = $PSScriptRoot

# --- discover repo root ---------------------------------------------------
if (-not $Repo) {
    $Repo = git rev-parse --show-toplevel 2>$null
    if ($LASTEXITCODE -ne 0) {
        if ($Init) {
            $Repo = (Get-Location).Path
            Write-Host "[gate] not a git repo; running 'git init' in $Repo"
            git init "$Repo" | Out-Null
        } else {
            Write-Warning "[gate] not inside a git repository. Re-run with -Repo <path> or -Init."
            exit 1
        }
    }
}
$Repo = (Resolve-Path $Repo).Path
$gitDir = git -C $Repo rev-parse --absolute-git-dir 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Warning "[gate] no valid git dir under $Repo"
    exit 1
}
if (-not (Test-Path $gitDir)) { $gitDir = Join-Path $Repo '.git' }
$hookDir = Join-Path $gitDir 'hooks'

Write-Host "== TRAE security gate installer =="
Write-Host "  repo      : $Repo"
Write-Host "  git dir   : $gitDir"
Write-Host "  hook dir  : $hookDir"
Write-Host "  strict    : $([bool]$Strict)"
Write-Host "  dry-run   : $([bool]$DryRun)"

# --- resolve powershell used by hooks -------------------------------------
$pwsh = (Get-Command powershell.exe -ErrorAction SilentlyContinue).Source
if (-not $pwsh) { $pwsh = 'powershell.exe' }

function Write-Hook {
    param([string]$Path, [string]$HookName, [string]$Content)
    if ($DryRun) {
        Write-Host "  [dry-run] would write $Path"
        Write-Host ($Content -split "`n" | ForEach-Object { "      | $_" })
        return
    }
    New-Item -ItemType Directory -Force -Path (Split-Path $Path) | Out-Null
    # ASCII + LF + no BOM, otherwise the sh shebang is broken under Windows git.
    [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "  installed $Path"
}

foreach ($hn in @('pre-commit','pre-push')) {
    $strictArg = if ($Strict) { ' -Strict' } else { '' }
    $content = @(
        '#!/bin/sh',
        "# TRAE security gate - $hn (generated by install-gate.ps1; overwrites manual hooks)",
        "exec `"$( $pwsh )`" -NoProfile -ExecutionPolicy Bypass -File `"$setup\gate-hook.ps1`" -Hook $hn -Repo `"$Repo`"$strictArg"
    ) -join "`n"
    Write-Hook -Path (Join-Path $hookDir $hn) -HookName $hn -Content ($content + "`n")
}

# place .semgrepignore at repo root if absent
$ignore = Join-Path $Repo '.semgrepignore'
if (-not (Test-Path $ignore)) {
    if ($DryRun) { Write-Host "  [dry-run] would copy .semgrepignore to $ignore" }
    else { Copy-Item (Join-Path $setup '.semgrepignore') $ignore -Force; Write-Host "  installed $ignore" }
}

Write-Host ""
Write-Host "== done. Your git hooks now gate commits/pushes with semgrep =="
if ($Strict) { Write-Host "   (Strict mode: warnings block the push too.)" }
Write-Host "   Test anytime: powershell -ExecutionPolicy Bypass -File `"$setup\security-scan.ps1`" -Target `"$Repo`""